### ISSUE TITLE
ZoomTape readme.txt links to old OpenCBM repo.

### ISSUE THREAD

**Issue by arnd-menge** [OpenCBM/OpenCBM#1]
The ZoomTape readme.txt (section 6) links to the old OpenCBM repo.

**Comment by silverdr** [comment]
Which file, exactly? The only `readme.txt` file seem to be in `internal/6502code`

**Comment by silverdr** [comment]
Or do you mean `ZoomTape-Manual-1.0_DRAFT.pdf`?

**Comment by arnd-menge** [comment]
https://github.com/OpenCBM/OpenCBM/blob/NewZoomTape/xuac/readme.txt

**Comment by arnd-menge** [comment]
Link fixed.
