### ISSUE TITLE
modprobe cbm hangs

### ISSUE THREAD

**Issue by wilhelmy** [OpenCBM/OpenCBM#94]
I've recompiled OpenCBM after about 8 years, now on an entirely different Linux box, and I still have the issue that loading the module hangs indefinitely (except now I can press Ctrl+C to get out of modprobe). The module is loaded correctly and I can copy floppies.

Any ideas?

**Comment by spiro-trikaliotis** [comment]
What kind of cable do you use? xa1541, xm1541, xu1541, xum1541, ...?

**Comment by wilhelmy** [comment]
It's something I presume is either XA1541 or XM1541 (could be X1541 but I'd be surprised if it still works on this modern parallel port). I got it off of ebay. Does it matter whether or not the cable is attached while loading the module?

**Comment by wilhelmy** [comment]
I think I waited 5s, but can't remember for sure (haven't rebooted since). Will update as soon as I do.
I noticed however that `cbmctrl reset` also hangs until I press Ctrl+C. Possibly related?

**Comment by spiro-trikaliotis** [comment]
Yes, on startup, the same function is caked as with cbmctrl reset. 
Without a connected device, the PC can hang for 5 seconds.

**Comment by spiro-trikaliotis** [comment]
Do you have any updates?

**Comment by wilhelmy** [comment]
I think it ended up working in the end but I honestly can't remember anymore. I'll close this and reopen with more info if it turns out I was wrong. Thank you!
